[package]
name = "PageHook-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ntapi = "0.4.1"
winapi = { version = "0.3.9", features = ["minwindef", "ntdef", "errhandlingapi", "memoryapi", "winnt", "excpt"] }